/* eslint-disable no-restricted-exports */
import React from 'react';

import './app.scss';
import '@/styles/globals.css';
import { HeaderBlock } from '@/globals/header';
import { getPayload } from 'payload';
import config from '@payload-config';
import { FooterBlock } from '@/globals/footer';
import { Footer } from '@/payload-types';

export const metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default async function RootLayout(props: { children: React.ReactNode }) {
    const { children } = props;
    const payload = await getPayload({ config });

    const HeaderProps = await payload.findGlobal({
        slug: 'header',
        depth: 1,
    });

    const FooterProps: Footer = await payload.findGlobal({
        slug: 'footer',
        depth: 1,
    });
    console.log('footerProps', FooterProps);

    return (
        <html lang="en">
            <body>
                <HeaderBlock HeaderProps={HeaderProps} />
                {children}
                <FooterBlock FooterProps={FooterProps} />
            </body>
        </html>
    );
}
