/* eslint-disable no-restricted-exports */
import React from 'react'


import './app.scss'
import '@/styles/globals.css'
import {HeaderBlock} from "@/globals/header";
import {getPayload} from "payload";
import config from "@payload-config";

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default async function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
    const payload = await getPayload({ config })

    const HeaderProps = await payload.findGlobal({
        slug: 'header',
        depth: 1,
    })
  return (
    <html lang="en">
      <body>
        <HeaderBlock HeaderProps={HeaderProps}/>
        {children}
      </body>
    </html>
  )
}
