/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    media: Media;
    googleReviewsFr: GoogleReviewsFr;
    googleReviewsIt: GoogleReviewsIt;
    googleReviewsEn: GoogleReviewsEn;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    googleReviewsFr: GoogleReviewsFrSelect<false> | GoogleReviewsFrSelect<true>;
    googleReviewsIt: GoogleReviewsItSelect<false> | GoogleReviewsItSelect<true>;
    googleReviewsEn: GoogleReviewsEnSelect<false> | GoogleReviewsEnSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'main-menu': MainMenu;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'fr' | 'it';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  layout?:
    | (
        | {
            title?: string | null;
            imagesArray?:
              | {
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'responsiveGallery';
          }
        | {
            bgImage?: (string | null) | Media;
            heading?: string | null;
            button?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: {
              titlePart?: string | null;
              titlePart1?: string | null;
              titlePart2?: string | null;
            };
            cardArray?:
              | {
                  card?: {
                    icon?: (string | null) | Media;
                    title?: string | null;
                    description?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            button?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'gridOrCarousel';
          }
        | {
            hideBoolean?: boolean | null;
            overallText?: string | null;
            starLogo?: (string | null) | Media;
            expandToggleTexts?: {
              expandLabel?: string | null;
              collapseLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviewCarousel';
          }
        | {
            title?: string | null;
            starEmptyLogo?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'overallRating';
          }
        | {
            headingGroup?: {
              heading?: string | null;
              starLogo?: (string | null) | Media;
              reviewsNumber?: number | null;
              reviewsText?: string | null;
              rating?: string | null;
              location?: string | null;
              description?: string | null;
              saveGroup?: {
                label?: string | null;
                url?: string | null;
                logo?: (string | null) | Media;
              };
              shareGroup?: {
                label?: string | null;
                url?: string | null;
                logo?: (string | null) | Media;
              };
            };
            description?: string | null;
            imagesArray?:
              | {
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            tabs?: {
              descriptionTab?: {
                tabTitle?: string | null;
                iconArray?:
                  | {
                      iconGroup?: {
                        icon?: (string | null) | Media;
                        label?: string | null;
                      };
                      id?: string | null;
                    }[]
                  | null;
                descriptionGroup?: {
                  heading?: string | null;
                  description?: string | null;
                };
                cautionGroup?: {
                  heading?: string | null;
                  descriptionCautionArray?:
                    | {
                        description?: string | null;
                        price?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                };
                button?: {
                  label?: string | null;
                  url?: string | null;
                };
                expandToggleTexts?: {
                  expandLabel?: string | null;
                  collapseLabel?: string | null;
                };
              };
              localisationTab?: {
                tabTitle?: string | null;
                longitude?: string | null;
                latitude?: string | null;
                adressGroup?: {
                  streetName?: string | null;
                  postCode?: string | null;
                  townName?: string | null;
                  country?: string | null;
                  houseNumber?: string | null;
                };
              };
              equipementsTab?:
                | {
                    equipement?: {
                      tabTitle?: string | null;
                      label?: string | null;
                      items?:
                        | {
                            label?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              reviewsTab?: {
                tabTitle?: string | null;
                overallGroup?: {
                  overallText?: string | null;
                  logo?: (string | null) | Media;
                };
                expandToggleTexts?: {
                  expandLabel?: string | null;
                  collapseLabel?: string | null;
                };
                starLogo?: (string | null) | Media;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'residencesPresentation';
          }
        | {
            telGroup?: {
              label?: string | null;
              number?: string | null;
            };
            emailGroup?: {
              label?: string | null;
              email?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInformation';
          }
        | {
            title?: string | null;
            selectionArray?:
              | {
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            formGroup?: {
              lastName?: {
                label?: string | null;
                placeholder?: string | null;
              };
              firstName?: {
                label?: string | null;
                placeholder?: string | null;
              };
              mail?: {
                label?: string | null;
                placeholder?: string | null;
              };
              tel?: {
                label?: string | null;
                placeholder?: string | null;
              };
              other?: {
                label?: string | null;
                placeholder?: string | null;
              };
              button?: {
                label?: string | null;
                url?: string | null;
              };
              calendarGroup?: {
                dynamicTitle?: {
                  singular?: string | null;
                  plural?: string | null;
                };
                dateSuffix?: string | null;
                deleteDateText?: string | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'bookingForm';
          }
        | {
            residencesArray?:
              | {
                  residenceGroup?: {
                    title?: string | null;
                    subheading?: string | null;
                    description?: string | null;
                    imageArray?:
                      | {
                          image?: (string | null) | Media;
                          id?: string | null;
                        }[]
                      | null;
                    iconArray?:
                      | {
                          card?: {
                            icon?: (string | null) | Media;
                            label?: string | null;
                          };
                          id?: string | null;
                        }[]
                      | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'residenceGeneral';
          }
        | {
            title?: string | null;
            subheading?: string | null;
            description?: string | null;
            imageSubheading?: string | null;
            imagesArray?:
              | {
                  images?: {
                    image?: (string | null) | Media;
                    label?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            button?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'restaurantCarousel';
          }
        | {
            title?: string | null;
            images?:
              | {
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            schedules?: {
              title?: string | null;
              schedulesArray?:
                | {
                    schedulesGroup?: {
                      day?: string | null;
                      timeAM?: string | null;
                      timePM?: string | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'restaurantMenu';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleReviewsFr".
 */
export interface GoogleReviewsFr {
  id: string;
  overallRating?: string | null;
  author: string;
  rating: number;
  review?: string | null;
  subReview?:
    | {
        rating?: number | null;
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  authorImage?: string | null;
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleReviewsIt".
 */
export interface GoogleReviewsIt {
  id: string;
  overallRating?: string | null;
  author: string;
  rating: number;
  review?: string | null;
  subReview?:
    | {
        rating?: number | null;
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  authorImage?: string | null;
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleReviewsEn".
 */
export interface GoogleReviewsEn {
  id: string;
  overallRating?: string | null;
  author: string;
  rating: number;
  review?: string | null;
  subReview?:
    | {
        rating?: number | null;
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  authorImage?: string | null;
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'googleReviewsFr';
        value: string | GoogleReviewsFr;
      } | null)
    | ({
        relationTo: 'googleReviewsIt';
        value: string | GoogleReviewsIt;
      } | null)
    | ({
        relationTo: 'googleReviewsEn';
        value: string | GoogleReviewsEn;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        responsiveGallery?:
          | T
          | {
              title?: T;
              imagesArray?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              bgImage?: T;
              heading?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gridOrCarousel?:
          | T
          | {
              title?:
                | T
                | {
                    titlePart?: T;
                    titlePart1?: T;
                    titlePart2?: T;
                  };
              cardArray?:
                | T
                | {
                    card?:
                      | T
                      | {
                          icon?: T;
                          title?: T;
                          description?: T;
                        };
                    id?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        reviewCarousel?:
          | T
          | {
              hideBoolean?: T;
              overallText?: T;
              starLogo?: T;
              expandToggleTexts?:
                | T
                | {
                    expandLabel?: T;
                    collapseLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        overallRating?:
          | T
          | {
              title?: T;
              starEmptyLogo?: T;
              id?: T;
              blockName?: T;
            };
        residencesPresentation?:
          | T
          | {
              headingGroup?:
                | T
                | {
                    heading?: T;
                    starLogo?: T;
                    reviewsNumber?: T;
                    reviewsText?: T;
                    rating?: T;
                    location?: T;
                    description?: T;
                    saveGroup?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          logo?: T;
                        };
                    shareGroup?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          logo?: T;
                        };
                  };
              description?: T;
              imagesArray?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              tabs?:
                | T
                | {
                    descriptionTab?:
                      | T
                      | {
                          tabTitle?: T;
                          iconArray?:
                            | T
                            | {
                                iconGroup?:
                                  | T
                                  | {
                                      icon?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                          descriptionGroup?:
                            | T
                            | {
                                heading?: T;
                                description?: T;
                              };
                          cautionGroup?:
                            | T
                            | {
                                heading?: T;
                                descriptionCautionArray?:
                                  | T
                                  | {
                                      description?: T;
                                      price?: T;
                                      id?: T;
                                    };
                              };
                          button?:
                            | T
                            | {
                                label?: T;
                                url?: T;
                              };
                          expandToggleTexts?:
                            | T
                            | {
                                expandLabel?: T;
                                collapseLabel?: T;
                              };
                        };
                    localisationTab?:
                      | T
                      | {
                          tabTitle?: T;
                          longitude?: T;
                          latitude?: T;
                          adressGroup?:
                            | T
                            | {
                                streetName?: T;
                                postCode?: T;
                                townName?: T;
                                country?: T;
                                houseNumber?: T;
                              };
                        };
                    equipementsTab?:
                      | T
                      | {
                          equipement?:
                            | T
                            | {
                                tabTitle?: T;
                                label?: T;
                                items?:
                                  | T
                                  | {
                                      label?: T;
                                      id?: T;
                                    };
                              };
                          id?: T;
                        };
                    reviewsTab?:
                      | T
                      | {
                          tabTitle?: T;
                          overallGroup?:
                            | T
                            | {
                                overallText?: T;
                                logo?: T;
                              };
                          expandToggleTexts?:
                            | T
                            | {
                                expandLabel?: T;
                                collapseLabel?: T;
                              };
                          starLogo?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        contactInformation?:
          | T
          | {
              telGroup?:
                | T
                | {
                    label?: T;
                    number?: T;
                  };
              emailGroup?:
                | T
                | {
                    label?: T;
                    email?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bookingForm?:
          | T
          | {
              title?: T;
              selectionArray?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              formGroup?:
                | T
                | {
                    lastName?:
                      | T
                      | {
                          label?: T;
                          placeholder?: T;
                        };
                    firstName?:
                      | T
                      | {
                          label?: T;
                          placeholder?: T;
                        };
                    mail?:
                      | T
                      | {
                          label?: T;
                          placeholder?: T;
                        };
                    tel?:
                      | T
                      | {
                          label?: T;
                          placeholder?: T;
                        };
                    other?:
                      | T
                      | {
                          label?: T;
                          placeholder?: T;
                        };
                    button?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    calendarGroup?:
                      | T
                      | {
                          dynamicTitle?:
                            | T
                            | {
                                singular?: T;
                                plural?: T;
                              };
                          dateSuffix?: T;
                          deleteDateText?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        residenceGeneral?:
          | T
          | {
              residencesArray?:
                | T
                | {
                    residenceGroup?:
                      | T
                      | {
                          title?: T;
                          subheading?: T;
                          description?: T;
                          imageArray?:
                            | T
                            | {
                                image?: T;
                                id?: T;
                              };
                          iconArray?:
                            | T
                            | {
                                card?:
                                  | T
                                  | {
                                      icon?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        restaurantCarousel?:
          | T
          | {
              title?: T;
              subheading?: T;
              description?: T;
              imageSubheading?: T;
              imagesArray?:
                | T
                | {
                    images?:
                      | T
                      | {
                          image?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        restaurantMenu?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              schedules?:
                | T
                | {
                    title?: T;
                    schedulesArray?:
                      | T
                      | {
                          schedulesGroup?:
                            | T
                            | {
                                day?: T;
                                timeAM?: T;
                                timePM?: T;
                              };
                          id?: T;
                        };
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleReviewsFr_select".
 */
export interface GoogleReviewsFrSelect<T extends boolean = true> {
  overallRating?: T;
  author?: T;
  rating?: T;
  review?: T;
  subReview?:
    | T
    | {
        rating?: T;
        category?: T;
        id?: T;
      };
  authorImage?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleReviewsIt_select".
 */
export interface GoogleReviewsItSelect<T extends boolean = true> {
  overallRating?: T;
  author?: T;
  rating?: T;
  review?: T;
  subReview?:
    | T
    | {
        rating?: T;
        category?: T;
        id?: T;
      };
  authorImage?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleReviewsEn_select".
 */
export interface GoogleReviewsEnSelect<T extends boolean = true> {
  overallRating?: T;
  author?: T;
  rating?: T;
  review?: T;
  subReview?:
    | T
    | {
        rating?: T;
        category?: T;
        id?: T;
      };
  authorImage?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navLogo?: (string | null) | Media;
  navItems?:
    | {
        itemsGroup?: {
          label?: string | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  navButton?: {
    label?: string | null;
    labelMobile?: string | null;
    url?: string | null;
  };
  language?: {
    languagePlaceholder?: string | null;
    languageChoice?:
      | {
          lang?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  blockDisplayBoolean?: boolean | null;
  logo?: (string | null) | Media;
  description?: string | null;
  button?: {
    label?: string | null;
    url?: string | null;
  };
  navArray?:
    | {
        navItem?: {
          label?: string | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  terms?: {
    label?: string | null;
    url?: string | null;
  };
  confidentiality?: {
    label?: string | null;
    url?: string | null;
  };
  socials?:
    | {
        social?: {
          icon?: (string | null) | Media;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  copyright?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navLogo?: T;
  navItems?:
    | T
    | {
        itemsGroup?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  navButton?:
    | T
    | {
        label?: T;
        labelMobile?: T;
        url?: T;
      };
  language?:
    | T
    | {
        languagePlaceholder?: T;
        languageChoice?:
          | T
          | {
              lang?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  blockDisplayBoolean?: T;
  logo?: T;
  description?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
      };
  navArray?:
    | T
    | {
        navItem?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  terms?:
    | T
    | {
        label?: T;
        url?: T;
      };
  confidentiality?:
    | T
    | {
        label?: T;
        url?: T;
      };
  socials?:
    | T
    | {
        social?:
          | T
          | {
              icon?: T;
              url?: T;
            };
        id?: T;
      };
  copyright?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}